version: '3.8'

services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:               # ✅ Add these two lines for the script to work
      DB_HOST: db
      DB_PORT: 5432
    command: [                # ✅ Replace the default start command with script execution
      "./wait-for-db.sh",
      "uvicorn", 
      "app.main:app", 
      "--host", "0.0.0.0", 
      "--port", "8000", 
      "--reload"
    ]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webhooks
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
